In [1]:
import numpy as np
import numpy.linalg as la

def householder(mat):
    m, n = mat.shape
    Q_T = np.eye(m)
    R = mat

    for k in range(n):
        #Computing v_k
        alpha_k = - np.sign(R[k,k]) * la.norm(R[k:, k])
        v_k = np.zeros(m)
        v_k[k:] = R[k:, k]
        v_k[k] -= alpha_k

        #Computing beta_k
        beta_k = np.dot(v_k, v_k)
        if beta_k == 0:
            continue

        #Compute R
        for j in range(k, n):
            gamma_j = np.dot(v_k, R[:, j])
            R[:,j] -= (2 * gamma_j / beta_k) * v_k

        #Compute Q^T
        for j in range(m):
            delta_j = np.dot(v_k, Q_T[:, j])
            Q_T[:,j] -= (2 * delta_j / beta_k) * v_k

    return Q_T.T, R

In [2]:
A = np.array([[1, 2], 
              [3, 9], 
              [2, 7]], dtype = float)
Q, R = householder(A)
print("Q = \n", Q)
print("Q^{-1} = \n", la.inv(Q))
print("QQ^T = \n", np.dot(Q, Q.T))
print("R = \n", R)
print("QR = \n", np.dot(Q,R))

Q = 
 [[-0.26726124  0.77151675  0.57735027]
 [-0.80178373  0.15430335 -0.57735027]
 [-0.53452248 -0.6172134   0.57735027]]
Q^{-1} = 
 [[-0.26726124 -0.80178373 -0.53452248]
 [ 0.77151675  0.15430335 -0.6172134 ]
 [ 0.57735027 -0.57735027  0.57735027]]
QQ^T = 
 [[ 1.00000000e+00  1.95242399e-16 -2.01213401e-17]
 [ 1.95242399e-16  1.00000000e+00  1.95242399e-16]
 [-2.01213401e-17  1.95242399e-16  1.00000000e+00]]
R = 
 [[-3.74165739e+00 -1.14922334e+01]
 [-8.88178420e-16 -1.38873015e+00]
 [-4.44089210e-16  0.00000000e+00]]
QR = 
 [[1. 2.]
 [3. 9.]
 [2. 7.]]


In [3]:
B = np.array([[4, 9 ,10], 
              [17, 5 , 1], 
              [0, 2, 11]], dtype = float)
Q, R = householder(B)
print("Q = \n", Q)
print("Q^{-1} = \n", la.inv(Q))
print("QQ^T = \n", np.dot(Q, Q.T))
print("R = \n", R)
print("QR = \n", np.dot(Q,R))

Q = 
 [[-0.22903933  0.94149141  0.24725475]
 [-0.97341717 -0.22152739 -0.05817759]
 [ 0.          0.25400697 -0.96720239]]
Q^{-1} = 
 [[-0.22903933 -0.97341717 -0.        ]
 [ 0.94149141 -0.22152739  0.25400697]
 [ 0.24725475 -0.05817759 -0.96720239]]
QQ^T = 
 [[ 1.00000000e+00 -1.06055711e-16  5.28325992e-17]
 [-1.06055711e-16  1.00000000e+00 -1.22639958e-17]
 [ 5.28325992e-17 -1.22639958e-17  1.00000000e+00]]
R = 
 [[-17.4642492   -6.92843985  -3.26381051]
 [  0.           7.87379967  11.98746338]
 [  0.           0.          -8.2248564 ]]
QR = 
 [[ 4.  9. 10.]
 [17.  5.  1.]
 [ 0.  2. 11.]]
