In [5]:
import numpy as np
import numpy.linalg as la

def householder(mat):
    m, n = mat.shape
    Q_T = np.eye(m)
    R = mat
    A = mat

    for k in range(n):
        #Computing v_k
        alpha_k = - np.sign(R[k,k]) * la.norm(R[k:, k])
        v_k = np.zeros(m)
        v_k[k:] = R[k:, k]
        v_k[k] -= alpha_k

        H = np.eye(m) - (2 * np.outer(v_k, v_k) / (v_k @ v_k.T))
        print("k = ", k)
        print("H = \n", H)
        print("v = ", v_k)
        A = H @ A
        print("A = \n", A)

        #Computing beta_k
        beta_k = np.dot(v_k, v_k)
        if beta_k == 0:
            continue

        print("beta_k = ", beta_k)

        #Compute R
        for j in range(k, n):
            gamma_j = np.dot(v_k, R[:, j])
            print("gamm_j = ", gamma_j)
            R[:,j] -= (2 * gamma_j / beta_k) * v_k

        #Compute Q^T
        for j in range(m):
            delta_j = np.dot(v_k, Q_T[:, j])
            Q_T[:,j] -= (2 * delta_j / beta_k) * v_k

    return Q_T.T, R, A

In [6]:
C = np.array([[1, 1, 1], 
              [1, 1, 0], 
              [1, 0, -1],
              [1, 0, 4]], dtype = float)

Q, R, A = householder(C)
print("Q = \n", Q)
print("R = \n", R)
print("A = \n", A)

k =  0
H = 
 [[-0.5        -0.5        -0.5        -0.5       ]
 [-0.5         0.83333333 -0.16666667 -0.16666667]
 [-0.5        -0.16666667  0.83333333 -0.16666667]
 [-0.5        -0.16666667 -0.16666667  0.83333333]]
v =  [3. 1. 1. 1.]
A = 
 [[-2.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [ 5.55111512e-17  3.33333333e-01 -1.00000000e+00]
 [ 8.32667268e-17 -6.66666667e-01 -2.00000000e+00]
 [ 1.11022302e-16 -6.66666667e-01  3.00000000e+00]]
beta_k =  12.0
gamm_j =  6.0
gamm_j =  4.0
gamm_j =  6.0
k =  1
H = 
 [[ 1.          0.          0.          0.        ]
 [ 0.         -0.33333333  0.66666667  0.66666667]
 [ 0.          0.66666667  0.66666667 -0.33333333]
 [ 0.          0.66666667 -0.33333333  0.66666667]]
v =  [ 0.          1.33333333 -0.66666667 -0.66666667]
A = 
 [[-2.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [ 1.11022302e-16 -1.00000000e+00  1.00000000e+00]
 [ 5.55111512e-17 -7.70988212e-17 -3.00000000e+00]
 [ 8.32667268e-17 -4.93432455e-17  2.00000000e+00]]
beta_k =  2

In [ ]:
B = np.array([[4, 9 ,10], 
              [17, 5 , 1], 
              [0, 2, 11]], dtype = float)
Q, R = householder(B)
print("Q = \n", Q)
print("Q^{-1} = \n", la.inv(Q))
print("QQ^T = \n", np.dot(Q, Q.T))
print("R = \n", R)
print("QR = \n", np.dot(Q,R))

In [ ]:
A = np.array([[1, 2], 
              [3, 9], 
              [2, 7]], dtype = float)
Q, R = householder(A)
print("Q = \n", Q)
print("Q^{-1} = \n", la.inv(Q))
print("QQ^T = \n", np.dot(Q, Q.T))
print("R = \n", R)
print("QR = \n", np.dot(Q,R))