In [57]:
import numpy as np
import numpy.linalg as la

A = np.array([[1, 1, 1],
              [3, 1, -3],
              [1, -2, -5]], dtype = float)

x0 = np.array([0, 1, 1], dtype = float)
x1 = np.array([3, -2, 1], dtype = float)
x2 = np.array([-2, -6, 1], dtype = float)

In [58]:
def NPI(A, x0, tol, max_iter):
    x = x0 / np.linalg.norm(x0)
    for k in range(max_iter):
        Ax = A @ x 
        x_new = Ax / np.linalg.norm(Ax)
        evalue = x_new.T @ A @ x_new

        if la.norm(x_new - x, np.inf) < tol:
            break
        x = x_new

    return evalue, x

In [59]:
evalue, evector = NPI(A, x0, 1.0e-8, 100)
print(evalue)
print(evector)

-6.2133494180048725
[-0.18297672  0.44143747  0.87843752]


In [60]:
evalue, evector = NPI(A, x1, 1.0e-8, 100)
print(evalue)
print(evector)

-6.2133494180048725
[ 0.18297672 -0.44143747 -0.87843752]


In [61]:
evalue, evector = NPI(A, x2, 1.0e-8, 100)
print(evalue)
print(evector)

-6.2133494180048725
[ 0.18297672 -0.44143747 -0.87843752]
