In [1]:
import numpy as np
import numpy.linalg as la

A = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]], dtype = float)

def cholesky(M):
    n = M.shape[0]
    L = np.zeros((n,n), dtype = float)

    for i in range(n):
        for j in range(i+1):
            if i == j:
                s = 0
                for k in range(i):
                    s += L[j, k] ** 2 
                L[i, j] = np.sqrt(M[i, j] - s) 
            elif i>j:
                s = 0
                for k in range(i):
                    s += L[i,k] * L[j,k]
                L[i, j] = (M[i, j] - s) / L[j, j]
    return L

L = cholesky(A)
print(L)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [2]:
print(L @ L.T)

[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]
