In [1]:
import numpy as np
import numpy.linalg as la

A = np.array([[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1],
             [-1, 1, 0],
             [-1, 0, 1],
             [0, -1, 1]], dtype = float)
b = np.array([1237, 1941, 2417, 711, 1177, 475], dtype = float)

In [2]:
N = np.dot(np.transpose(A), A)
z = np.dot(np.transpose(A), b)
print(N)
print(z)

[[ 3. -1. -1.]
 [-1.  3. -1.]
 [-1. -1.  3.]]
[-651. 2177. 4069.]


In [3]:
def cholesky(M):
    n = M.shape[0]
    L = np.zeros((n,n), dtype = float)

    for i in range(n):
        for j in range(i+1):
            if i == j:
                s = 0
                for k in range(i):
                    s += L[j, k] ** 2 
                L[i, j] = np.sqrt(M[i, j] - s) 
            elif i>j:
                s = 0
                for k in range(i):
                    s += L[i,k] * L[j,k]
                L[i, j] = (M[i, j] - s) / L[j, j]
    return L

def back_sub(A, b):
    n = len(b)
    x = np.zeros(len(b), dtype = float)
    for i in range(n - 1, -1, -1):
        if A[i, i] == 0:
            raise ValueError("Matrix is singular")
        x[i] = b[i]
        for j in range(i+1, n):
            x[i] -= A[i, j] * x[j]
        x[i] = x[i] / A[i, i]
    return x

def fwd_elim(A, b):
    n = len(b)
    x = np.zeros(len(b), dtype = float)
    
    for i in range(n):
        if A[i, i] == 0:
            raise ValueError("Matrix is singular")
        x[i] = b[i]
        for j in range(0, i):
            x[i] -= A[i, j] * x[j]
        x[i] = x[i] / A[i, i]
    
    return x

L = cholesky(N)
w = fwd_elim(L, z)
x = back_sub(np.transpose(L), w)

print(x)

[1236. 1943. 2416.]


In [4]:
y = np.dot(A, x)
r = b - y
print(r)

[ 1. -2.  1.  4. -3.  2.]


In [5]:
print(np.dot(np.transpose(A), r))
print(np.dot(r, A))

[-6.82121026e-13  2.27373675e-13 -6.82121026e-13]
[-6.82121026e-13  2.27373675e-13 -6.82121026e-13]


In [6]:
P = np.dot(np.dot(A, la.inv(np.dot(np.transpose(A), A))), np.transpose(A))
print(P)

[[ 0.5   0.25  0.25 -0.25 -0.25  0.  ]
 [ 0.25  0.5   0.25  0.25  0.   -0.25]
 [ 0.25  0.25  0.5   0.    0.25  0.25]
 [-0.25  0.25  0.    0.5   0.25 -0.25]
 [-0.25  0.    0.25  0.25  0.5   0.25]
 [ 0.   -0.25  0.25 -0.25  0.25  0.5 ]]


In [7]:
print(y - np.dot(P, b))

[ 4.54747351e-13  2.27373675e-13  4.54747351e-13 -2.27373675e-13
  0.00000000e+00  2.27373675e-13]


In [8]:
P_perp = np.eye(6) - P
print(P_perp)

[[ 0.5  -0.25 -0.25  0.25  0.25  0.  ]
 [-0.25  0.5  -0.25 -0.25  0.    0.25]
 [-0.25 -0.25  0.5   0.   -0.25 -0.25]
 [ 0.25 -0.25  0.    0.5  -0.25  0.25]
 [ 0.25  0.   -0.25 -0.25  0.5  -0.25]
 [ 0.    0.25 -0.25  0.25 -0.25  0.5 ]]


In [9]:
print(r - np.dot(P_perp, b))

[-4.54747351e-13 -2.27373675e-13 -4.54747351e-13  2.27373675e-13
  0.00000000e+00 -2.27373675e-13]
