In [2]:
import numpy as np
import numpy.linalg as la

A = np.array([[0.01, 1, 5.5],
             [1, 2, 0.004],
             [0, 0, 3]], dtype = float)

b = np.array([1, 3, 5], dtype = float)
n = len(b)
x = np.zeros(n)

<font size = "4"> Given a matrix $A$ of size $m\times n$,  $B = A.\texttt{reshape}(p, q)$ will reshape the matrix $A$ into a new matrix $B$ of size $p\times q$. 
Note that $mn = pq$ for this to work. Giving a $-1$ in the first argument will imply that the compiler can select the number of rows according to the number of columns given. </font>


In [3]:
#Create the augmented matrix [A|b]

Ab = np.hstack([A,b.reshape(-1,1)], dtype = float)

<font size = "4"> Now we loop over the columns and find the pivot (largest element) in each column and grab the index of the pivot using np.argmax(). Then, we swap the rows if necessary and further, we will reduce the matrix A to its row reduced echelon form </font>

In [4]:
for i in range(n):
    row_ind = np.argmax(Ab[i:, i])+i # Ab[i:, i] will be the vector consisting of the elements of the i'th column of Ab from row i and below.
    if Ab[row_ind, i] == 0:
        print("Pivoting failed, matrix singular")
    if row_ind != i:               # If the pivot element is not in the current row i, then swap the rows so that the pivot is now on the diagonal.
        temp = Ab[i].copy()        # Store row i temporarily
        Ab[i] = Ab[row_ind]        # Replace row i with row row_ind
        Ab[row_ind] = temp         # Replace row row_ind with the original row i
    
# Now, we make the entries below the pivot to be 0.    
    for j in range(i+1, n):
        z = Ab[j, i] / Ab[i, i]
        for k in range(i, n+1):
            Ab[j, k] = Ab[j, k] - z * Ab[i, k]
print(Ab)

[[1.00000e+00 2.00000e+00 4.00000e-03 3.00000e+00]
 [0.00000e+00 9.80000e-01 5.49996e+00 9.70000e-01]
 [0.00000e+00 0.00000e+00 3.00000e+00 5.00000e+00]]


<font size = "4"> This completes the pivoting process and should yield a upper triangular matrix $A$ augmented with the right-hand side $b$. Now, we simply need to perform back substitution to solve for $x$ </font>

In [8]:
A_rref = Ab[0:3, 0:3]
b_mod = Ab[:,3]
print(A_rref)
print(b_mod)


[[1.00000e+00 2.00000e+00 4.00000e-03]
 [0.00000e+00 9.80000e-01 5.49996e+00]
 [0.00000e+00 0.00000e+00 3.00000e+00]]
[3.   0.97 5.  ]
