In [21]:
import numpy as np
import numpy.linalg as la

A = np.array([[1.5, 3, 2],
              [3, 1.05, 6.8],
              [4.8, 0.001, 1]], dtype = float)

b = np.array([0.5, 1, 0.01],dtype = float)

def LU_dcomp(matrix):
    
    n = matrix.shape[0]
    P = np.eye(n) # Creates an identity matrix of size n x n. We will save the permutation matrix P here.
    U = matrix.copy()
    L = np.eye(n)
    
    for i in range(n):
        row_ind = np.argmax(U[i:, i]) + i   # mat[i:, i] will be the vector consisting of the elements of the i'th column of mat from row i and below.
        if row_ind != i:                    # If the pivot element is not in the current row i, then swap the rows so that the pivot is now on the diagonal.
            U[[i, row_ind], :] = U[[row_ind, i], :]
            P[[i, row_ind], :] = P[[row_ind, i], :]
            L[[i, row_ind], :i] = L[[row_ind, i], :i]
            
        # Now, we make the entries below the pivot to be 0.    
        for j in range(i+1, n):
            z = U[j, i] / U[i, i]
            L[j, i] = z
            for k in range(i, n):
                U[j, k] = U[j, k] - z * U[i, k]                
    return L,U,P

def back_sub(A, b):
    n = len(b)
    x = np.zeros(len(b), dtype = float)
    for i in range(n - 1, -1, -1):
        if A[i, i] == 0:
            raise ValueError("Matrix is singular")
        x[i] = b[i]
        for j in range(i+1, n):
            x[i] -= A[i, j] * x[j]
        x[i] = x[i] / A[i, i]
    return x

def fwd_elim(A, b):
    n = len(b)
    x = np.zeros(len(b), dtype = float)
    
    for i in range(n):
        if A[i, i] == 0:
            raise ValueError("Matrix is singular")
        x[i] = b[i]
        for j in range(0, i):
            x[i] -= A[i, j] * x[j]
        x[i] = x[i] / A[i, i]
    
    return x

In [22]:
L_A, U_A, P_A = LU_dcomp(A)
#print("L =", L_A, "\nU =", U_A, "\nP =", P_A)
print(la.inv(P_A) @ L_A @ U_A)

[[1.50e+00 3.00e+00 2.00e+00]
 [3.00e+00 1.05e+00 6.80e+00]
 [4.80e+00 1.00e-03 1.00e+00]]


In [20]:
y = fwd_elim(L_A, np.dot(P_A, b))
x = back_sub(U_A, y)
z = la.solve(A, b)

print(x)
print(z)

[-0.02852104  0.08304855  0.14681796]
[-0.02852104  0.08304855  0.14681796]
