In [4]:
import numpy as np
import numpy.linalg as la

A = np.array([[1.5, 3, 2],
              [3, 1.05, 6.8],
              [4.8, 0.001, 1]], dtype = float)

def LU_dcomp(matrix):
    
    n = matrix.shape[0]
    P = np.eye(n) # Creates an identity matrix of size n x n. We will save the permutation matrix P here.
    U = matrix.copy()
    
    for i in range(n):
        row_ind = np.argmax(U[i:, i]) + i   # mat[i:, i] will be the vector consisting of the elements of the i'th column of mat from row i and below.
        if row_ind != i:                    # If the pivot element is not in the current row i, then swap the rows so that the pivot is now on the diagonal.
            temp = U[i].copy()              # Store row i temporarily
            U[i] = U[row_ind]               # Replace row i with row row_ind
            U[row_ind] = temp               # Replace row row_ind with the original row i

            temp = P[i].copy()            
            P[i] = P[row_ind]           
            P[row_ind] = temp             

        # Now, we make the entries below the pivot to be 0.    
        for j in range(i+1, n):
            z = U[j, i] / U[i, i]
            for k in range(i, n):
                U[j, k] = U[j, k] - z * U[i, k]

        # The unit lower triangular matrix is now given by L = PAU^{-1}

        L = np.dot(np.dot(P, A), la.inv(U))
        
    return L,U,P
    
L_A, U_A, P_A = LU_dcomp(A)

print(L_A)
print(U_A)
print(P_A)
print(np.dot(la.inv(P_A), np.dot(L_A, U_A)))

[[ 1.00000000e+00 -1.69128310e-20  0.00000000e+00]
 [ 3.12500000e-01  1.00000000e+00  0.00000000e+00]
 [ 6.25000000e-01  3.49828107e-01  1.00000000e+00]]
[[4.80000000e+00 1.00000000e-03 1.00000000e+00]
 [0.00000000e+00 2.99968750e+00 1.68750000e+00]
 [0.00000000e+00 0.00000000e+00 5.58466507e+00]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1.50e+00 3.00e+00 2.00e+00]
 [3.00e+00 1.05e+00 6.80e+00]
 [4.80e+00 1.00e-03 1.00e+00]]
